# Generated by Django 2.0.10 on 2019-02-01 19:11

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import taxonomies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default='', max_length=50, verbose_name='算法编号')),
                ('name', models.CharField(max_length=100, verbose_name='算法名称')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击数')),
                ('favor_number', models.IntegerField(default=0, verbose_name='收藏数')),
                ('brief', models.TextField(max_length=500, verbose_name='算法简介')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='算法详情')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='algorithms/images/', verbose_name='算法封面图')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=models.SET(taxonomies.models.get_sentinel_category), to='taxonomies.Category', verbose_name='算法类目')),
            ],
            options={
                'verbose_name': '算法',
                'verbose_name_plural': '算法',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.Algorithm', verbose_name='算法')),
            ],
            options={
                'verbose_name': '轮播算法',
                'verbose_name_plural': '轮播算法',
            },
        ),
    ]
